# Generated by Django 4.1.7 on 2023-04-07 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficiales', '0002_newrecruits_alter_oficiales_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newrecruits',
            name='game',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='newrecruits',
            name='message',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='newrecruits',
            name='rules',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='newrecruits',
            name='socialmedia',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
