# Generated by Django 4.1.7 on 2023-04-07 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficiales', '0003_newrecruits_game_newrecruits_message_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_informed', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='newrecruits',
            name='date_inscription',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
