# Generated by Django 4.1.7 on 2023-04-07 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oficiales', '0004_availability_newrecruits_date_inscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='oficiales.oficiales'),
        ),
    ]
