# Generated by Django 4.1.7 on 2023-04-08 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficiales', '0005_availability_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='newrecruits',
            name='rules_knowledge',
            field=models.CharField(choices=[('Ninguno', 'Ninguno'), ('Básico', 'Básico'), ('Regular', 'Regular'), ('Bueno', 'Bueno'), ('Muy Bueno', 'Muy Bueno'), ('Excelente', 'Excelente')], max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='newrecruits',
            name='game',
            field=models.CharField(choices=[('Ninguno', 'Ninguno'), ('Básico', 'Básico'), ('Regular', 'Regular'), ('Bueno', 'Bueno'), ('Muy Bueno', 'Muy Bueno'), ('Excelente', 'Excelente')], max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='newrecruits',
            name='message',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='newrecruits',
            name='socialmedia',
            field=models.CharField(choices=[('Web FAA', 'Web FAA'), ('Facebook', 'Facebook'), ('Instagram', 'Instagram'), ('Twitter', 'Twitter'), ('Otro', 'Otro')], max_length=150, null=True),
        ),
    ]
