# Generated by Django 4.1.7 on 2023-04-12 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficiales', '0006_newrecruits_rules_knowledge_alter_newrecruits_game_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='availability',
            old_name='status',
            new_name='partido1',
        ),
        migrations.AddField(
            model_name='availability',
            name='partido2',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=100, null=True),
        ),
    ]
