# Generated by Django 4.1.7 on 2023-04-12 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficiales', '0008_calendar'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='horario',
            field=models.CharField(choices=[('13hs', '13hs'), ('15.30hs', '15.30hs')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='local',
            field=models.CharField(choices=[('Corsarios', 'Corsarios'), ('Cruzados', 'Cruzados'), ('Jabalies', 'Jabalies'), ('Legionarios', 'Legionarios'), ('Osos Polares', 'Osos Polares'), ('Tiburones', 'Tiburones')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='visitante',
            field=models.CharField(choices=[('Corsarios', 'Corsarios'), ('Cruzados', 'Cruzados'), ('Jabalies', 'Jabalies'), ('Legionarios', 'Legionarios'), ('Osos Polares', 'Osos Polares'), ('Tiburones', 'Tiburones')], max_length=100, null=True),
        ),
    ]
