# Generated by Django 4.1.7 on 2023-04-25 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('oficiales', '0010_reviews_availability_game2_alter_calendar_horario'),
    ]

    operations = [
        migrations.AddField(
            model_name='oficiales',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='availability',
            name='partido1',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='Si', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='availability',
            name='partido2',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='Si', max_length=100, null=True),
        ),
    ]
