# Generated by Django 4.1.7 on 2023-04-25 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('oficiales', '0011_oficiales_user_alter_availability_partido1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='availability',
            old_name='game2',
            new_name='turno',
        ),
        migrations.AlterField(
            model_name='availability',
            name='name',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
