# Generated by Django 4.1.7 on 2023-04-25 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oficiales', '0012_rename_game2_availability_turno_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='availability',
            old_name='name',
            new_name='user',
        ),
    ]
