# Generated by Django 4.1.7 on 2023-04-25 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oficiales', '0014_remove_availability_turno'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='turno',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='oficiales.calendar'),
        ),
    ]
