# Generated by Django 4.1.7 on 2023-04-25 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oficiales', '0015_availability_turno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='turno',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='oficiales.calendar'),
        ),
    ]
