# Generated by Django 4.1.7 on 2023-04-26 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficiales', '0016_alter_availability_turno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='fecha',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
