# Generated by Django 4.1.7 on 2023-04-26 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oficiales', '0017_alter_calendar_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availability',
            name='user',
        ),
        migrations.AddField(
            model_name='availability',
            name='oficial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='oficiales.oficiales'),
        ),
    ]
