# Generated by Django 4.1.7 on 2023-04-26 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oficiales', '0018_remove_availability_user_availability_oficial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='turno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oficiales.calendar'),
        ),
    ]
