# Generated by Django 4.1.7 on 2023-05-02 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oficiales', '0021_rename_partido_availability_partido1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='availability',
            old_name='first_game',
            new_name='fecha',
        ),
        migrations.RemoveField(
            model_name='availability',
            name='second_game',
        ),
        migrations.RemoveField(
            model_name='oficiales',
            name='user',
        ),
    ]
