# Generated by Django 4.1.7 on 2023-05-02 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oficiales', '0023_fechas_alter_availability_fecha'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fechas',
        ),
    ]
