# Generated by Django 4.1.7 on 2023-05-02 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficiales', '0024_delete_fechas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='fecha',
            field=models.DateField(),
        ),
    ]
