# Generated by Django 4.1.7 on 2023-05-02 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficiales', '0027_remove_availability_date_informed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='date_informed',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='availability',
            name='available',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='Si', max_length=100, null=True),
        ),
    ]
