# Generated by Django 4.1.7 on 2023-05-03 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oficiales', '0030_remove_availability_horario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendar',
            name='horario',
        ),
        migrations.AddField(
            model_name='calendar',
            name='horario',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='oficiales.time'),
        ),
    ]
