# Generated by Django 4.1.7 on 2023-05-03 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oficiales', '0031_remove_calendar_horario_calendar_horario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availability',
            name='calendar',
        ),
        migrations.AddField(
            model_name='availability',
            name='match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oficiales.calendar'),
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='horario',
        ),
        migrations.AddField(
            model_name='calendar',
            name='horario',
            field=models.ManyToManyField(to='oficiales.time'),
        ),
    ]
