# Generated by Django 4.1.7 on 2023-05-03 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficiales', '0032_remove_availability_calendar_availability_match_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendar',
            name='horario',
        ),
        migrations.AddField(
            model_name='calendar',
            name='horario',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
