# Generated by Django 4.1.7 on 2023-05-03 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oficiales', '0033_remove_calendar_horario_calendar_horario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='horario',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='oficiales.time'),
        ),
    ]
