# Generated by Django 4.1.7 on 2023-05-03 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficiales', '0034_alter_calendar_horario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='name',
            field=models.CharField(choices=[('13hs', '13hs'), ('15.30hs', '15.30hs')], max_length=50, null=True),
        ),
    ]
