# Generated by Django 4.1.7 on 2023-05-04 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficiales', '0038_remove_calendar_game_remove_time_fecha_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendar',
            name='horario',
        ),
        migrations.AddField(
            model_name='calendar',
            name='game',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='availability',
            name='first_game',
            field=models.CharField(choices=[('13hs', '13hs'), ('15.30hs', '15.30hs')], default='13hs', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='availability',
            name='second_game',
            field=models.CharField(choices=[('13hs', '13hs'), ('15.30hs', '15.30hs')], default='15.30hs', max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name='Time',
        ),
    ]
