# Generated by Django 4.1.7 on 2023-05-04 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oficiales', '0039_remove_calendar_horario_calendar_game_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turno', models.CharField(choices=[('13hs', '13hs'), ('15.30hs', '15.30hs')], max_length=50, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='availability',
            name='first_game',
            field=models.CharField(default='13hs', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='availability',
            name='second_game',
            field=models.CharField(default='15.30hs', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='calendar',
            name='horario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='oficiales.time'),
        ),
    ]
