# Generated by Django 4.1.7 on 2023-05-04 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oficiales', '0040_time_alter_availability_first_game_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calendar',
            old_name='game',
            new_name='day',
        ),
        migrations.RemoveField(
            model_name='availability',
            name='first_game',
        ),
        migrations.AlterField(
            model_name='availability',
            name='second_game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_game', to='oficiales.time'),
        ),
    ]
