# Generated by Django 4.1.7 on 2023-05-10 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('oficiales', '0046_oficiales_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teams',
            name='name',
        ),
        migrations.AddField(
            model_name='teams',
            name='team',
            field=models.CharField(choices=[('Corsarios', 'Corsarios'), ('Cruzados', 'Cruzados'), ('Jabalies', 'Jabalies'), ('Legionarios', 'Legionarios'), ('Osos Polares', 'Osos Polares'), ('Tiburones', 'Tiburones')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='oficiales',
            name='profile_pic',
            field=models.ImageField(blank=True, default='user_logo_nbg.pngT', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='oficiales',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
