# Generated by Django 4.1.7 on 2023-05-11 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oficiales', '0049_alter_availability_first_game_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availability',
            name='first_game',
        ),
        migrations.RemoveField(
            model_name='availability',
            name='second_game',
        ),
        migrations.AlterField(
            model_name='availability',
            name='oficial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='oficiales.oficiales'),
        ),
    ]
