# Generated by Django 4.1.7 on 2023-05-11 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oficiales', '0050_remove_availability_first_game_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='oficial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='oficiales.oficiales'),
        ),
    ]
