# Generated by Django 4.1.7 on 2023-05-15 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oficiales', '0051_alter_availability_oficial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='official',
            new_name='official_position',
        ),
        migrations.AddField(
            model_name='reviews',
            name='player_number',
            field=models.IntegerField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='reviews',
            name='tiempo',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='official_name',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.SET_NULL, to='oficiales.oficiales'),
        ),
    ]
