# Generated by Django 4.1.7 on 2023-05-15 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficiales', '0052_rename_official_reviews_official_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='play_numb',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='player_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
