# Generated by Django 4.1.7 on 2023-05-26 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oficiales', '0054_alter_oficiales_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='game_date',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='oficiales.calendar'),
        ),
    ]
