# Generated by Django 4.1.7 on 2023-05-28 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oficiales', '0056_alter_availability_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('R', 'R'), ('U', 'U'), ('HL', 'HL'), ('LJ', 'LJ'), ('SJ', 'SJ'), ('FJ', 'FJ'), ('BJ', 'BJ')], max_length=50, null=True)),
                ('game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='oficiales.calendar')),
                ('official', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='oficiales.oficiales')),
            ],
        ),
    ]
